version: '3'

# Define services
services:
  # Mysql Service
  mysql:
    image: 'mysql:latest'
    restart: always
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./sql-files:/sql-files

# Networks to be created for communication between containers
networks:
  backend:
